name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: change the ending style for Linux
        run:  apt install dos2unix  
              dos2unix ./scripts/buildprod.sh
      - name: build the app
        run: ./scripts/buildprod.sh
