name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Unit testing
        run: go test ./... -cover
  style:
    name: style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: check for style
        run: test -z $(go fmt ./...)
      
      - name: install linter
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      
      - name: check linting 
        run : staticcheck ./...